// Code generated by github.com/pm1381/sirish. DO NOT EDIT.
// Version

package internal

import (
	"context"

	apm "go.elastic.co/apm/v2"
)

type TestModuleSirishWrapperImpl struct {
	// TODO: Visitor supports generics. add generics to template
	name          string
	wrapped       TestModule
	interfaceName string
	tagType       string
}

func NewTestModuleSirishWrapperImpl(
	name string,
	wrapped TestModule,
	tagType string,
) *TestModuleSirishWrapperImpl {

	return &TestModuleSirishWrapperImpl{
		name:          name,
		tagType:       tagType,
		interfaceName: "TestModule",
		wrapped:       wrapped,
	}
}

func (w *TestModuleSirishWrapperImpl) DoTest1(ctx_0_0 context.Context, req DoTest1Request, span int) (string, error) {
	if apm.TransactionFromContext(ctx_0_0) == nil {
		// for handling scenarios where the incoming context does not have any apm transaction
		ctx_0_0ApmTx := apm.DefaultTracer().StartTransaction("Transaction.TestModule.DoTest1", w.tagType)
		ctx_0_0 = apm.ContextWithTransaction(ctx_0_0, ctx_0_0ApmTx)
		defer ctx_0_0ApmTx.End()
	}
	var DoTest1SpnSkOW_2_0 *apm.Span
	DoTest1SpnSkOW_2_0, ctx_0_0 = apm.StartSpan(ctx_0_0, "TestModule.DoTest1", w.tagType)
	DoTest1SpnSkOW_2_0.Context.SetLabel("label", w.name)
	defer DoTest1SpnSkOW_2_0.End()
	DoTest1ResUnKuiU_0_0, DoTest1ResUnglCc_1_0 := w.wrapped.DoTest1(ctx_0_0, req, span)
	if DoTest1ResUnglCc_1_0 != nil {
		apm.CaptureError(ctx_0_0, DoTest1ResUnglCc_1_0).SetSpan(DoTest1SpnSkOW_2_0)
		DoTest1SpnSkOW_2_0.Outcome = "failure"
	} else {
		DoTest1SpnSkOW_2_0.Outcome = "success"
	}
	return DoTest1ResUnKuiU_0_0, DoTest1ResUnglCc_1_0
}

func (w *TestModuleSirishWrapperImpl) DoTest2(ctx_0_0 context.Context, req *DoTest2Request) (*DoTest2Response, error) {
	if apm.TransactionFromContext(ctx_0_0) == nil {
		// for handling scenarios where the incoming context does not have any apm transaction
		ctx_0_0ApmTx := apm.DefaultTracer().StartTransaction("Transaction.TestModule.DoTest2", w.tagType)
		ctx_0_0 = apm.ContextWithTransaction(ctx_0_0, ctx_0_0ApmTx)
		defer ctx_0_0ApmTx.End()
	}
	var span *apm.Span
	span, ctx_0_0 = apm.StartSpan(ctx_0_0, "TestModule.DoTest2", w.tagType)
	span.Context.SetLabel("label", w.name)
	defer span.End()
	DoTest2ResUnBuMU_0_0, DoTest2ResUnviEr_1_0 := w.wrapped.DoTest2(ctx_0_0, req)
	if DoTest2ResUnviEr_1_0 != nil {
		apm.CaptureError(ctx_0_0, DoTest2ResUnviEr_1_0).SetSpan(span)
		span.Outcome = "failure"
	} else {
		span.Outcome = "success"
	}
	return DoTest2ResUnBuMU_0_0, DoTest2ResUnviEr_1_0
}

func (w *TestModuleSirishWrapperImpl) DoNext() (ctx context.Context, res interface{}, err error) {
	ctx, res, err = w.wrapped.DoNext()
	return ctx, res, err
}
