// Code generated by sirish. DO NOT EDIT.
// Version

package internal

import (
	context "context"

	apm "go.elastic.co/apm/v2"
)

type TestModuleSirishWrapperImpl struct {
	// TODO: Visitor supports generics. add generics to template
	name          string
	wrapped       TestModule
	interfaceName string
	tagType       string
}

func NewTestModuleSirishWrapperImpl(
	name string,
	wrapped TestModule,
	tagType string,
) *TestModuleSirishWrapperImpl {

	return &TestModuleSirishWrapperImpl{
		name:          name, // TODO: at the moment of writing this, there is no need to have name. remove it
		tagType:       tagType,
		interfaceName: "TestModule",
		wrapped:       wrapped,
	}
}

func (w *TestModuleSirishWrapperImpl) DoTest1(ctx_0_0 context.Context, req DoTest1Request, span int) (string, error) {
	var DoTest1SpncSoZ_2_0 *apm.Span
	DoTest1SpncSoZ_2_0, ctx_0_0 = apm.StartSpan(ctx_0_0, "TestModule.DoTest1", w.tagType)
	defer DoTest1SpncSoZ_2_0.End()
	DoTest1ResUnwkcU_0_0, DoTest1ResUnmXMw_1_0 := w.wrapped.DoTest1(ctx_0_0, req, span)
	return DoTest1ResUnwkcU_0_0, DoTest1ResUnmXMw_1_0
}

func (w *TestModuleSirishWrapperImpl) DoTest2(ctx_0_0 context.Context, req *DoTest2Request) (*DoTest2Response, error) {
	var span *apm.Span
	span, ctx_0_0 = apm.StartSpan(ctx_0_0, "TestModule.DoTest2", w.tagType)
	defer span.End()
	DoTest2ResUnDgQb_0_0, DoTest2ResUnqFDs_1_0 := w.wrapped.DoTest2(ctx_0_0, req)
	return DoTest2ResUnDgQb_0_0, DoTest2ResUnqFDs_1_0
}

func (w *TestModuleSirishWrapperImpl) DoNext() (ctx context.Context, res interface{}, err error) {
	ctx, res, err = w.wrapped.DoNext()
	return ctx, res, err
}
