// Code generated by sirish. DO NOT EDIT.
// Version 0.1.1

package internal

import (
	context "context"

	apm "go.elastic.co/apm/v2"
)

type TestModuleSirishWrapperImpl struct {
	// TODO: Visitor supports generics. add generics to template
	name          string
	wrapped       TestModule
	interfaceName string
	tagType       string
}

func NewTestModuleSirishWrapperImpl(
	name string,
	wrapped TestModule,
	tagType string,
) *TestModuleSirishWrapperImpl {

	return &TestModuleSirishWrapperImpl{
		name:          name,
		tagType:       tagType,
		interfaceName: "TestModule",
		wrapped:       wrapped,
	}
}

func (w *TestModuleSirishWrapperImpl) DoTest1(ctx_0_0 context.Context, req DoTest1Request, span int) (string, error) {
	var DoTest1SpnrWpR_2_0 *apm.Span
	DoTest1SpnrWpR_2_0, ctx_0_0 = apm.StartSpan(ctx_0_0, "TestModule.DoTest1", w.tagType)
	DoTest1SpnrWpR_2_0.Context.SetLabel("label", w.name)
	defer DoTest1SpnrWpR_2_0.End()
	DoTest1ResUnkYfz_0_0, DoTest1ResUnULaT_1_0 := w.wrapped.DoTest1(ctx_0_0, req, span)
	if DoTest1ResUnULaT_1_0 != nil {
		apm.CaptureError(ctx_0_0, DoTest1ResUnULaT_1_0).SetSpan(DoTest1SpnrWpR_2_0)
		DoTest1SpnrWpR_2_0.Outcome = "failure"
	} else {
		DoTest1SpnrWpR_2_0.Outcome = "success"
	}
	return DoTest1ResUnkYfz_0_0, DoTest1ResUnULaT_1_0
}

func (w *TestModuleSirishWrapperImpl) DoTest2(ctx_0_0 context.Context, req *DoTest2Request) (*DoTest2Response, error) {
	var span *apm.Span
	span, ctx_0_0 = apm.StartSpan(ctx_0_0, "TestModule.DoTest2", w.tagType)
	span.Context.SetLabel("label", w.name)
	defer span.End()
	DoTest2ResUnMIZr_0_0, DoTest2ResUnMBhh_1_0 := w.wrapped.DoTest2(ctx_0_0, req)
	if DoTest2ResUnMBhh_1_0 != nil {
		apm.CaptureError(ctx_0_0, DoTest2ResUnMBhh_1_0).SetSpan(span)
		span.Outcome = "failure"
	} else {
		span.Outcome = "success"
	}
	return DoTest2ResUnMIZr_0_0, DoTest2ResUnMBhh_1_0
}

func (w *TestModuleSirishWrapperImpl) DoNext() (ctx context.Context, res interface{}, err error) {
	ctx, res, err = w.wrapped.DoNext()
	return ctx, res, err
}
